{
 "title": "New dashboard Copy2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Producer Event Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "my-metrics.producer.events.mean_rate"
    }
   ]
  },
  {
   "title": "Consumer Event Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "my-metrics.consumer.events.mean_rate"
    }
   ]
  },
  {
   "title": "Consumer Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "my-metrics.consumer.processing_time.mean"
    }
   ]
  },
  {
   "title": "Wait Time in Kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "my-metrics.wait-time-in-kafka.p95"
    }
   ]
  }
 ]
}